Map<String, String> iconOfSubservices = {
  'Pagar': 'assets/icons/subservices/fence.png',
  'Listrik': 'assets/icons/subservices/electric.png',
  'Renovasi': 'assets/icons/subservices/brick.png',
  'Pengecatan': 'assets/icons/subservices/roller-brush.png',
  'Tangga': 'assets/icons/subservices/stairs.png',
  'Sketsa': 'assets/icons/subservices/sketch.png',
  'Las': 'assets/icons/subservices/welding.png',
  'Sapu': 'assets/icons/subservices/broom.png',
  'Wallpaper': 'assets/icons/subservices/wallpaper.png',
  'Kulkas': 'assets/icons/subservices/refrigerator.png',
  'AC': 'assets/icons/subservices/air-conditioner.png',
  'CCTV': 'assets/icons/subservices/cctv.png',
  'Mesin cuci': 'assets/icons/subservices/washing-machine.png',
  'Dinamo': 'assets/icons/subservices/dynamo.png',
  'Aki': 'assets/icons/subservices/battery.png',
  'Dispenser': 'assets/icons/subservices/water-dispenser.png',
  'Komputer': 'assets/icons/subservices/computer.png',
  'Sofa': 'assets/icons/subservices/couch.png',
  'Lemari': 'assets/icons/subservices/cupboard.png',
  'Kitchen set': 'assets/icons/subservices/kitchen.png',
  'Meja': 'assets/icons/subservices/table.png',
  'Kaca': 'assets/icons/subservices/glass.png'};